# Transport

Ministry officials assigned to the aquarium require reliable transportation to execute their diverse range of responsibilities. This includes tasks such as animal sampling, banking of monetary transactions, and facilitating the transport of critical equipment to and from the aquarium premises.

## Available vehicles

At the Aquarium, Ministry officials utilize a single cab Land Cruiser, known as the "Cruiser," shared with the Environment sub-division at NATMiRC. If required, they can also access other MFMR vehicles, such as a Toyota Corolla sedan - hereafter referred to as the "Corolla". The Cruiser is generally used for tasks like animal sampling or collection, while the Corolla is employed for other official MFMR duties. Both these vehicles are parked in the NATMiRC garage, located in the research center's southern wing.

**Only MFMR officials with drivers licenses are allowed to use MFMR vehicles**.

### Booking a vehicle {#sec-book-vehicle}

1.  Obtain a signed, "Official vehicle trip authority and log statement" from the relevant administration officer at the Administration office (referred to as the "Transport officer" throughout this chapter or in reference to this chapter).
    -   *To be completed prior to using a vehicle and must be kept in the vehicle during use*.
    -   *A separate sheet is issued for each vehicle to be used over a period of one month*.
    -   *Details of all drivers and passengers that will be using the assigned vehicle should be included in each statement*.
    -   *Authorized trip destinations and times should be indicated on the statement*.
2.  Approach the Transport officer to apply for a fuel pin.
    -   *This will be sent to the applicant via text message when it is ready*.
    -   *Used to fuel the MFMR vehicles*.
    -   *Only needs to be done once, preferably before using any of the MFMR vehicles*.

-   **Items described in Steps 3-6 can be obtained from/completed by the Fisheries research technician (FRT) employed at the Aquarium when the Cruiser needs to be used and, from the Transport officer if a FRT is not in place or if the Corolla needs to be used by Aquarium staff. New copies of the log book and request form (steps 3 and 4) can also be made using the photocopier in the Administration office, using old versions as a template**.

3.  Obtain a "Trip log" book for the assigned car.
    -   *This should be completed everyday for trips exceeding one day and after every trip completed within a day*.
    -   *A new book will only be needed once the current book is full*.
4.  Complete an official "Request for transport" form.
    -   *Should be completed prior to using the vehicle*.
5.  Collect the car keys.
6.  A vehicle inspection has to be conducted before leaving NATMiRC.
    -   *Minor damage or missing vehicle accessories will be documented*.
    -   *In the event of any major damage, vehicle use will not be permitted*.

### Vehicle use

7.  At this stage, the vehicle is ready for use.
8.  Visit the nearest service station and ensure the cars tyre pressure is correct.
    -   *This may be excessive for short trips (\<30km) but, frequently checking a routinely used car's tyre pressure is standard practice*.
    -   *Fill the cars tyres up and proceed if there are no signs of a serious puncture*.
9.  Read the cars fuel gauge and fill it up if necessary.

-   **Steps 8 and 9 should be completed before travelling**

10. Drive out to your destination.

### Vehicle return {#sec-vehicle-return}

11. If the car is empty (or near empty) after returning to Swakopmund from your trip, fill it up before returning to the NATMiRC garage.
    -   *Keep all fuel receipts*.
    -   *Otherwise skip to next step*.
12. Upon return to the NATMiRC garage, the vehicle has to be cleaned if it is dirty.
    -   *Can be done using the fire hydrant outside the NATMiRC garage*.
    -   *If already clean, skip to next step*.
13. Another inspection has to be done.
14. Ensure all documents from steps 2-4 are complete and return them, along with the trip authority statement (step 1) and the car keys, to the FRT or Transport officer.

## Beach driving

## Accidents

## Trailer use

### Sample tank {#sec-sam-tank}
